version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: sausage
      POSTGRES_PASSWORD: codingSausage!42
      POSTGRES_DB: DirtyPawsCookbook
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  #recipeservice:
  #  build: 
  #      context: ../recipeservice
  #      dockerfile: Dockerfile
  #  image: recipe-service:dev
  #  container_name: "recipe-service"

volumes:
  postgres-data: